### ISSUE TITLE
不起作用 Obsidian 1.5.4

### ISSUE THREAD

**Issue by QSC707** [liuxingyu521/obsidian-plugin-cursor-goaway#1]
cursor-goaway 1.2.0

没有效果

安装方式：Obsidian的社区插件市场

很抱歉我编程知识很有限，或许是我理解不到位，能有简便一点的安装方式吗

这个插件对于我来说很重要，非常感谢你的开发

**Comment by liuxingyu521** [comment]
你好，我现在用的 v1.5.8 版本的 Obsidian，测试没有问题。你升级下客户端试试呢？

**Comment by liuxingyu521** [comment]
这个问题复现了，请从插件商店更新到最新版 v1.3.0 试试。还有问题可再来反馈~
