### ISSUE TITLE
支持从文件列表打开的场景？

### ISSUE THREAD

**Issue by ycbrd** [liuxingyu521/obsidian-plugin-cursor-goaway#2]
感谢作者大大，对强迫症极度友好！

我自己测试，在通过文内链接和快速切换来打开文件时，该插件都起作用。但是通过文件列表打开时不起作用。能不能麻烦您考虑支持从文件列表打开的场景？

**Comment by liuxingyu521** [comment]
谢谢你的反馈~ 最新一版 v1.3.0 做了更新修复，可以下载试试。

**Comment by ycbrd** [comment]
您好，我安装新版本时，main.js被Windows系统视为病毒，会被自动删除。这可能是什么缘故呢？

**Comment by liuxingyu521** [comment]
> 您好，我安装新版本时，main.js被Windows系统视为病毒，会被自动删除。这可能是什么缘故呢？

在 Obsidian 应用里的插件商店里安装更新

**Comment by ycbrd** [comment]
您好，在插件商店安装也打不开。

https://github.com/liuxingyu521/obsidian-plugin-cursor-goaway/assets/105804326/42c19252-f18c-4950-bd34-13d5cfc09545
